version: '3'

services:

  app:
    build :
      context: .
      dockerfile: ./Dockerfile
    links:
    - mariadb:mariadb 
    environment:
      SPRING_DATASOURCE_URL: jdbc:mariadb://mariadb:3306/jpastander
      SPRING_DATASOURCE_PASSWORD: 1234
    restart: always
    ports:
      - 8080:8080
    volumes:
      - ./:/app/
    depends_on:
      - mariadb

  mariadb:
    image: mariadb
    volumes:
      - ./:/app/
    ports:
      - 3306:3306
    restart: always
    environment:
      MARIADB_DATABASE : jpastander
      MARIADB_ROOT_PASSWORD : 1234
      MARIADB_ROOT_HOST : mariadb
      MARIADB_USER: woojin
      MARIADB_PASSWORD: 1234
